stages:
  - unit
  - integration
  - report

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"

unit_tests:
  stage: unit
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd src/ServicesUnitTests
    - dotnet restore
    - dotnet test --logger "trx;LogFileName=unit-tests.trx" --results-directory ./TestResults --collect:"XPlat Code Coverage"
  artifacts:
    when: always
    paths:
      - src/ServicesUnitTests/allure-results
      - src/ServicesUnitTests/TestResults
    expire_in: 1 week

integration_tests:
  stage: integration
  image: mcr.microsoft.com/dotnet/sdk:8.0
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd src/RepositoriesTests
    - dotnet restore
    - dotnet test --logger "trx;LogFileName=integration-tests.trx" --results-directory ./TestResults
  artifacts:
    when: always
    paths:
      - src/RepositoriesTests/allure-results
      - src/RepositoriesTests/TestResults
    expire_in: 1 week
  needs:
    - job: unit_tests
      artifacts: true

merge_allure:
  stage: report
  image: alpine:latest
  script:
    - apk add --no-cache bash
    - mkdir -p merged-allure-results
    - cp -r src/ServicesUnitTests/allure-results/* merged-allure-results/ || true
    - cp -r src/RepositoriesTests/allure-results/* merged-allure-results/ || true
  artifacts:
    paths:
      - merged-allure-results
    expire_in: 1 week
  needs:
    - unit_tests
    - integration_tests
