{
 "title": "New dashboard",
 "time": { "from": "2025-10-12T17:30:40.000Z", "to": "2025-10-12T17:40:24.000Z" },
 "panels": [
  {
   "title": "New panel",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "k6_http_req_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bytes written",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "npgsql_db_client_commands_bytes_written",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(scenario) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "0.99 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(scenario) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(scenario) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(scenario) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "0.75 quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(scenario) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "0.5 quantile"
    }
   ]
  }
 ]
}