/*
 * CompetitiveBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CompetitiveFrontend.OpenAPIClient.Client;
using CompetitiveFrontend.OpenAPIClient.Model;

namespace CompetitiveFrontend.OpenAPIClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthorizationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountLoginDTO"> (optional)</param>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO ApiV1AuthLoginPost(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO? competitiveBackendBackendUsageObjectsAccountLoginDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountLoginDTO"> (optional)</param>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> ApiV1AuthLoginPostWithHttpInfo(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO? competitiveBackendBackendUsageObjectsAccountLoginDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountCreationDTO"> (optional)</param>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO ApiV1AuthRegisterPost(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO? competitiveBackendBackendUsageObjectsAccountCreationDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountCreationDTO"> (optional)</param>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> ApiV1AuthRegisterPostWithHttpInfo(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO? competitiveBackendBackendUsageObjectsAccountCreationDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthorizationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountLoginDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> ApiV1AuthLoginPostAsync(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO? competitiveBackendBackendUsageObjectsAccountLoginDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountLoginDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO>> ApiV1AuthLoginPostWithHttpInfoAsync(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO? competitiveBackendBackendUsageObjectsAccountLoginDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountCreationDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> ApiV1AuthRegisterPostAsync(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO? competitiveBackendBackendUsageObjectsAccountCreationDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountCreationDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO>> ApiV1AuthRegisterPostWithHttpInfoAsync(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO? competitiveBackendBackendUsageObjectsAccountCreationDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthorizationApi : IAuthorizationApiSync, IAuthorizationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AuthorizationApi : IDisposable, IAuthorizationApi
    {
        private CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AuthorizationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AuthorizationApi(string basePath)
        {
            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                new CompetitiveFrontend.OpenAPIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AuthorizationApi(CompetitiveFrontend.OpenAPIClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AuthorizationApi(CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient client, CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient asyncClient, CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountLoginDTO"> (optional)</param>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        public CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO ApiV1AuthLoginPost(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO? competitiveBackendBackendUsageObjectsAccountLoginDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> localVarResponse = ApiV1AuthLoginPostWithHttpInfo(competitiveBackendBackendUsageObjectsAccountLoginDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountLoginDTO"> (optional)</param>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> ApiV1AuthLoginPostWithHttpInfo(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO? competitiveBackendBackendUsageObjectsAccountLoginDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsAccountLoginDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO>("/api/v1/auth/login", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1AuthLoginPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountLoginDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        public async System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> ApiV1AuthLoginPostAsync(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO? competitiveBackendBackendUsageObjectsAccountLoginDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1AuthLoginPostWithHttpInfoAsync(competitiveBackendBackendUsageObjectsAccountLoginDTO, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountLoginDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO>> ApiV1AuthLoginPostWithHttpInfoAsync(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO? competitiveBackendBackendUsageObjectsAccountLoginDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountLoginDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsAccountLoginDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO>("/api/v1/auth/login", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1AuthLoginPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountCreationDTO"> (optional)</param>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        public CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO ApiV1AuthRegisterPost(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO? competitiveBackendBackendUsageObjectsAccountCreationDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> localVarResponse = ApiV1AuthRegisterPostWithHttpInfo(competitiveBackendBackendUsageObjectsAccountCreationDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountCreationDTO"> (optional)</param>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> ApiV1AuthRegisterPostWithHttpInfo(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO? competitiveBackendBackendUsageObjectsAccountCreationDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsAccountCreationDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO>("/api/v1/auth/register", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1AuthRegisterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountCreationDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO</returns>
        public async System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> ApiV1AuthRegisterPostAsync(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO? competitiveBackendBackendUsageObjectsAccountCreationDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1AuthRegisterPostWithHttpInfoAsync(competitiveBackendBackendUsageObjectsAccountCreationDTO, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsAccountCreationDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO>> ApiV1AuthRegisterPostWithHttpInfoAsync(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO? competitiveBackendBackendUsageObjectsAccountCreationDTO = default(CompetitiveBackend.BackendUsage.Objects.AccountCreationDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsAccountCreationDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<CompetitiveBackend.BackendUsage.Objects.AuthSuccessResultDTO>("/api/v1/auth/register", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1AuthRegisterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
