/*
 * CompetitiveBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CompetitiveFrontend.OpenAPIClient.Client;
using CompetitiveFrontend.OpenAPIClient.Model;

namespace CompetitiveFrontend.OpenAPIClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPlayerRewardsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO> ApiV1PlayersPlayerIDRewardsGet(int playerID, int? page = default(int?), int? count = default(int?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> ApiV1PlayersPlayerIDRewardsGetWithHttpInfo(int playerID, int? page = default(int?), int? count = default(int?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="rewardDescriptionID"> (optional)</param>
        /// <returns></returns>
        void ApiV1PlayersPlayerIDRewardsPut(int playerID, int? rewardDescriptionID = default(int?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="rewardDescriptionID"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1PlayersPlayerIDRewardsPutWithHttpInfo(int playerID, int? rewardDescriptionID = default(int?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rewardID"></param>
        /// <param name="playerID"></param>
        /// <returns></returns>
        void ApiV1PlayersPlayerIDRewardsRewardIDDelete(int rewardID, string playerID);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rewardID"></param>
        /// <param name="playerID"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1PlayersPlayerIDRewardsRewardIDDeleteWithHttpInfo(int rewardID, string playerID);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO> ApiV1PlayersSelfRewardsGet(int? page = default(int?), int? count = default(int?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> ApiV1PlayersSelfRewardsGetWithHttpInfo(int? page = default(int?), int? count = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPlayerRewardsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> ApiV1PlayersPlayerIDRewardsGetAsync(int playerID, int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>>> ApiV1PlayersPlayerIDRewardsGetWithHttpInfoAsync(int playerID, int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="rewardDescriptionID"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1PlayersPlayerIDRewardsPutAsync(int playerID, int? rewardDescriptionID = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="rewardDescriptionID"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1PlayersPlayerIDRewardsPutWithHttpInfoAsync(int playerID, int? rewardDescriptionID = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rewardID"></param>
        /// <param name="playerID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1PlayersPlayerIDRewardsRewardIDDeleteAsync(int rewardID, string playerID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rewardID"></param>
        /// <param name="playerID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1PlayersPlayerIDRewardsRewardIDDeleteWithHttpInfoAsync(int rewardID, string playerID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> ApiV1PlayersSelfRewardsGetAsync(int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>>> ApiV1PlayersSelfRewardsGetWithHttpInfoAsync(int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPlayerRewardsApi : IPlayerRewardsApiSync, IPlayerRewardsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PlayerRewardsApi : IDisposable, IPlayerRewardsApi
    {
        private CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerRewardsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PlayerRewardsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerRewardsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PlayerRewardsApi(string basePath)
        {
            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                new CompetitiveFrontend.OpenAPIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerRewardsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PlayerRewardsApi(CompetitiveFrontend.OpenAPIClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerRewardsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PlayerRewardsApi(CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient client, CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient asyncClient, CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        public List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO> ApiV1PlayersPlayerIDRewardsGet(int playerID, int? page = default(int?), int? count = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> localVarResponse = ApiV1PlayersPlayerIDRewardsGetWithHttpInfo(playerID, page, count);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> ApiV1PlayersPlayerIDRewardsGetWithHttpInfo(int playerID, int? page = default(int?), int? count = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("playerID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(playerID)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>>("/api/v1/players/{playerID}/rewards", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersPlayerIDRewardsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> ApiV1PlayersPlayerIDRewardsGetAsync(int playerID, int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayersPlayerIDRewardsGetWithHttpInfoAsync(playerID, page, count, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>>> ApiV1PlayersPlayerIDRewardsGetWithHttpInfoAsync(int playerID, int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("playerID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(playerID)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>>("/api/v1/players/{playerID}/rewards", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersPlayerIDRewardsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="rewardDescriptionID"> (optional)</param>
        /// <returns></returns>
        public void ApiV1PlayersPlayerIDRewardsPut(int playerID, int? rewardDescriptionID = default(int?))
        {
            ApiV1PlayersPlayerIDRewardsPutWithHttpInfo(playerID, rewardDescriptionID);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="rewardDescriptionID"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1PlayersPlayerIDRewardsPutWithHttpInfo(int playerID, int? rewardDescriptionID = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("playerID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(playerID)); // path parameter
            if (rewardDescriptionID != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "rewardDescriptionID", rewardDescriptionID));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/api/v1/players/{playerID}/rewards", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersPlayerIDRewardsPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="rewardDescriptionID"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1PlayersPlayerIDRewardsPutAsync(int playerID, int? rewardDescriptionID = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayersPlayerIDRewardsPutWithHttpInfoAsync(playerID, rewardDescriptionID, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playerID"></param>
        /// <param name="rewardDescriptionID"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1PlayersPlayerIDRewardsPutWithHttpInfoAsync(int playerID, int? rewardDescriptionID = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("playerID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(playerID)); // path parameter
            if (rewardDescriptionID != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "rewardDescriptionID", rewardDescriptionID));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PutAsync<Object>("/api/v1/players/{playerID}/rewards", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersPlayerIDRewardsPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rewardID"></param>
        /// <param name="playerID"></param>
        /// <returns></returns>
        public void ApiV1PlayersPlayerIDRewardsRewardIDDelete(int rewardID, string playerID)
        {
            ApiV1PlayersPlayerIDRewardsRewardIDDeleteWithHttpInfo(rewardID, playerID);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rewardID"></param>
        /// <param name="playerID"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1PlayersPlayerIDRewardsRewardIDDeleteWithHttpInfo(int rewardID, string playerID)
        {
            // verify the required parameter 'playerID' is set
            if (playerID == null)
                throw new CompetitiveFrontend.OpenAPIClient.Client.ApiException(400, "Missing required parameter 'playerID' when calling PlayerRewardsApi->ApiV1PlayersPlayerIDRewardsRewardIDDelete");

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("rewardID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(rewardID)); // path parameter
            localVarRequestOptions.PathParameters.Add("playerID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(playerID)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/v1/players/{playerID}/rewards/{rewardID}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersPlayerIDRewardsRewardIDDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rewardID"></param>
        /// <param name="playerID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1PlayersPlayerIDRewardsRewardIDDeleteAsync(int rewardID, string playerID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayersPlayerIDRewardsRewardIDDeleteWithHttpInfoAsync(rewardID, playerID, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rewardID"></param>
        /// <param name="playerID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1PlayersPlayerIDRewardsRewardIDDeleteWithHttpInfoAsync(int rewardID, string playerID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'playerID' is set
            if (playerID == null)
                throw new CompetitiveFrontend.OpenAPIClient.Client.ApiException(400, "Missing required parameter 'playerID' when calling PlayerRewardsApi->ApiV1PlayersPlayerIDRewardsRewardIDDelete");


            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("rewardID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(rewardID)); // path parameter
            localVarRequestOptions.PathParameters.Add("playerID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(playerID)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.DeleteAsync<Object>("/api/v1/players/{playerID}/rewards/{rewardID}", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersPlayerIDRewardsRewardIDDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        public List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO> ApiV1PlayersSelfRewardsGet(int? page = default(int?), int? count = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> localVarResponse = ApiV1PlayersSelfRewardsGetWithHttpInfo(page, count);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> ApiV1PlayersSelfRewardsGetWithHttpInfo(int? page = default(int?), int? count = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>>("/api/v1/players/self/rewards", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersSelfRewardsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> ApiV1PlayersSelfRewardsGetAsync(int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayersSelfRewardsGetWithHttpInfoAsync(page, count, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>>> ApiV1PlayersSelfRewardsGetWithHttpInfoAsync(int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<List<CompetitiveBackend.BackendUsage.Objects.PlayerRewardDTO>>("/api/v1/players/self/rewards", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersSelfRewardsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
