/*
 * CompetitiveBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CompetitiveFrontend.OpenAPIClient.Client;
using CompetitiveFrontend.OpenAPIClient.Model;

namespace CompetitiveFrontend.OpenAPIClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompetitionApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="filter"> (optional)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.CompetitionDTO&gt;</returns>
        List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> ApiV1CompetitionsGet(int? page = default(int?), int? count = default(int?), string? filter = default(string?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="filter"> (optional)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.CompetitionDTO&gt;</returns>
        ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> ApiV1CompetitionsGetWithHttpInfo(int? page = default(int?), int? count = default(int?), string? filter = default(string?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.CompetitionDTO</returns>
        CompetitiveBackend.BackendUsage.Objects.CompetitionDTO ApiV1CompetitionsIdGet(int id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.CompetitionDTO</returns>
        ApiResponse<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> ApiV1CompetitionsIdGetWithHttpInfo(int id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        void ApiV1CompetitionsIdLevelGet(int id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1CompetitionsIdLevelGetWithHttpInfo(int id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="file"> (optional)</param>
        /// <returns></returns>
        void ApiV1CompetitionsIdLevelPatch(int id, System.IO.Stream? file = default(System.IO.Stream?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="file"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1CompetitionsIdLevelPatchWithHttpInfo(int id, System.IO.Stream? file = default(System.IO.Stream?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO"> (optional)</param>
        /// <returns></returns>
        void ApiV1CompetitionsIdPatch(int id, CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO? competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1CompetitionsIdPatchWithHttpInfo(int id, CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO? competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionDTO"> (optional)</param>
        /// <returns></returns>
        void ApiV1CompetitionsPut(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO? competitiveBackendBackendUsageObjectsCompetitionDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1CompetitionsPutWithHttpInfo(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO? competitiveBackendBackendUsageObjectsCompetitionDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompetitionApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="filter"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.CompetitionDTO&gt;</returns>
        System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> ApiV1CompetitionsGetAsync(int? page = default(int?), int? count = default(int?), string? filter = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="filter"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.CompetitionDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>>> ApiV1CompetitionsGetWithHttpInfoAsync(int? page = default(int?), int? count = default(int?), string? filter = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.CompetitionDTO</returns>
        System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> ApiV1CompetitionsIdGetAsync(int id, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.CompetitionDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> ApiV1CompetitionsIdGetWithHttpInfoAsync(int id, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1CompetitionsIdLevelGetAsync(int id, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1CompetitionsIdLevelGetWithHttpInfoAsync(int id, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1CompetitionsIdLevelPatchAsync(int id, System.IO.Stream? file = default(System.IO.Stream?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1CompetitionsIdLevelPatchWithHttpInfoAsync(int id, System.IO.Stream? file = default(System.IO.Stream?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1CompetitionsIdPatchAsync(int id, CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO? competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1CompetitionsIdPatchWithHttpInfoAsync(int id, CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO? competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1CompetitionsPutAsync(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO? competitiveBackendBackendUsageObjectsCompetitionDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1CompetitionsPutWithHttpInfoAsync(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO? competitiveBackendBackendUsageObjectsCompetitionDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompetitionApi : ICompetitionApiSync, ICompetitionApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CompetitionApi : IDisposable, ICompetitionApi
    {
        private CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CompetitionApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public CompetitionApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompetitionApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public CompetitionApi(string basePath)
        {
            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                new CompetitiveFrontend.OpenAPIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompetitionApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public CompetitionApi(CompetitiveFrontend.OpenAPIClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompetitionApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public CompetitionApi(CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient client, CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient asyncClient, CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="filter"> (optional)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.CompetitionDTO&gt;</returns>
        public List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> ApiV1CompetitionsGet(int? page = default(int?), int? count = default(int?), string? filter = default(string?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> localVarResponse = ApiV1CompetitionsGetWithHttpInfo(page, count, filter);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="filter"> (optional)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.CompetitionDTO&gt;</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> ApiV1CompetitionsGetWithHttpInfo(int? page = default(int?), int? count = default(int?), string? filter = default(string?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>>("/api/v1/competitions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="filter"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.CompetitionDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> ApiV1CompetitionsGetAsync(int? page = default(int?), int? count = default(int?), string? filter = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsGetWithHttpInfoAsync(page, count, filter, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional)</param>
        /// <param name="count"> (optional)</param>
        /// <param name="filter"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.CompetitionDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>>> ApiV1CompetitionsGetWithHttpInfoAsync(int? page = default(int?), int? count = default(int?), string? filter = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<List<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>>("/api/v1/competitions", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.CompetitionDTO</returns>
        public CompetitiveBackend.BackendUsage.Objects.CompetitionDTO ApiV1CompetitionsIdGet(int id)
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> localVarResponse = ApiV1CompetitionsIdGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.CompetitionDTO</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> ApiV1CompetitionsIdGetWithHttpInfo(int id)
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>("/api/v1/competitions/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.CompetitionDTO</returns>
        public async System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> ApiV1CompetitionsIdGetAsync(int id, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsIdGetWithHttpInfoAsync(id, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.CompetitionDTO)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>> ApiV1CompetitionsIdGetWithHttpInfoAsync(int id, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<CompetitiveBackend.BackendUsage.Objects.CompetitionDTO>("/api/v1/competitions/{id}", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        public void ApiV1CompetitionsIdLevelGet(int id)
        {
            ApiV1CompetitionsIdLevelGetWithHttpInfo(id);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1CompetitionsIdLevelGetWithHttpInfo(int id)
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/v1/competitions/{id}/level", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsIdLevelGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1CompetitionsIdLevelGetAsync(int id, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsIdLevelGetWithHttpInfoAsync(id, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1CompetitionsIdLevelGetWithHttpInfoAsync(int id, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<Object>("/api/v1/competitions/{id}/level", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsIdLevelGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="file"> (optional)</param>
        /// <returns></returns>
        public void ApiV1CompetitionsIdLevelPatch(int id, System.IO.Stream? file = default(System.IO.Stream?))
        {
            ApiV1CompetitionsIdLevelPatchWithHttpInfo(id, file);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="file"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1CompetitionsIdLevelPatchWithHttpInfo(int id, System.IO.Stream? file = default(System.IO.Stream?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (file != null)
            {
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/v1/competitions/{id}/level", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsIdLevelPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1CompetitionsIdLevelPatchAsync(int id, System.IO.Stream? file = default(System.IO.Stream?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsIdLevelPatchWithHttpInfoAsync(id, file, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1CompetitionsIdLevelPatchWithHttpInfoAsync(int id, System.IO.Stream? file = default(System.IO.Stream?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (file != null)
            {
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PatchAsync<Object>("/api/v1/competitions/{id}/level", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsIdLevelPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO"> (optional)</param>
        /// <returns></returns>
        public void ApiV1CompetitionsIdPatch(int id, CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO? competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO?))
        {
            ApiV1CompetitionsIdPatchWithHttpInfo(id, competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1CompetitionsIdPatchWithHttpInfo(int id, CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO? competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/v1/competitions/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsIdPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1CompetitionsIdPatchAsync(int id, CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO? competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsIdPatchWithHttpInfoAsync(id, competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1CompetitionsIdPatchWithHttpInfoAsync(int id, CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO? competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionUpdateRequestDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsCompetitionUpdateRequestDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PatchAsync<Object>("/api/v1/competitions/{id}", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsIdPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionDTO"> (optional)</param>
        /// <returns></returns>
        public void ApiV1CompetitionsPut(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO? competitiveBackendBackendUsageObjectsCompetitionDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO?))
        {
            ApiV1CompetitionsPutWithHttpInfo(competitiveBackendBackendUsageObjectsCompetitionDTO);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1CompetitionsPutWithHttpInfo(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO? competitiveBackendBackendUsageObjectsCompetitionDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsCompetitionDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/api/v1/competitions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1CompetitionsPutAsync(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO? competitiveBackendBackendUsageObjectsCompetitionDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsPutWithHttpInfoAsync(competitiveBackendBackendUsageObjectsCompetitionDTO, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsCompetitionDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1CompetitionsPutWithHttpInfoAsync(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO? competitiveBackendBackendUsageObjectsCompetitionDTO = default(CompetitiveBackend.BackendUsage.Objects.CompetitionDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsCompetitionDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PutAsync<Object>("/api/v1/competitions", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
