/*
 * CompetitiveBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CompetitiveFrontend.OpenAPIClient.Client;
using CompetitiveFrontend.OpenAPIClient.Model;

namespace CompetitiveFrontend.OpenAPIClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPlayerParticipationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> ApiV1CompetitionsCompetitionIDParticipationsGet(int competitionID, int? page = default(int?), int? count = default(int?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1CompetitionsCompetitionIDParticipationsGetWithHttpInfo(int competitionID, int? page = default(int?), int? count = default(int?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <returns></returns>
        void ApiV1CompetitionsCompetitionIDParticipationsProfileIDDelete(int profileID, int competitionID);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1CompetitionsCompetitionIDParticipationsProfileIDDeleteWithHttpInfo(int profileID, int competitionID);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO</returns>
        CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO ApiV1CompetitionsCompetitionIDParticipationsProfileIDGet(int profileID, int competitionID);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO</returns>
        ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> ApiV1CompetitionsCompetitionIDParticipationsProfileIDGetWithHttpInfo(int profileID, int competitionID);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="score"> (optional)</param>
        /// <returns></returns>
        void ApiV1CompetitionsCompetitionIDParticipationsPut(int competitionID, int? score = default(int?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="score"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1CompetitionsCompetitionIDParticipationsPutWithHttpInfo(int competitionID, int? score = default(int?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> ApiV1PlayersSelfParticipationsGet(int? page = default(int?), int? count = default(int?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1PlayersSelfParticipationsGetWithHttpInfo(int? page = default(int?), int? count = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPlayerParticipationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1CompetitionsCompetitionIDParticipationsGetAsync(int competitionID, int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>>> ApiV1CompetitionsCompetitionIDParticipationsGetWithHttpInfoAsync(int competitionID, int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1CompetitionsCompetitionIDParticipationsProfileIDDeleteAsync(int profileID, int competitionID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1CompetitionsCompetitionIDParticipationsProfileIDDeleteWithHttpInfoAsync(int profileID, int competitionID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO</returns>
        System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> ApiV1CompetitionsCompetitionIDParticipationsProfileIDGetAsync(int profileID, int competitionID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1CompetitionsCompetitionIDParticipationsProfileIDGetWithHttpInfoAsync(int profileID, int competitionID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="score"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1CompetitionsCompetitionIDParticipationsPutAsync(int competitionID, int? score = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="score"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1CompetitionsCompetitionIDParticipationsPutWithHttpInfoAsync(int competitionID, int? score = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1PlayersSelfParticipationsGetAsync(int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>>> ApiV1PlayersSelfParticipationsGetWithHttpInfoAsync(int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPlayerParticipationApi : IPlayerParticipationApiSync, IPlayerParticipationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PlayerParticipationApi : IDisposable, IPlayerParticipationApi
    {
        private CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerParticipationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PlayerParticipationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerParticipationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PlayerParticipationApi(string basePath)
        {
            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                new CompetitiveFrontend.OpenAPIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerParticipationApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PlayerParticipationApi(CompetitiveFrontend.OpenAPIClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerParticipationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PlayerParticipationApi(CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient client, CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient asyncClient, CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        public List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> ApiV1CompetitionsCompetitionIDParticipationsGet(int competitionID, int? page = default(int?), int? count = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> localVarResponse = ApiV1CompetitionsCompetitionIDParticipationsGetWithHttpInfo(competitionID, page, count);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1CompetitionsCompetitionIDParticipationsGetWithHttpInfo(int competitionID, int? page = default(int?), int? count = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("competitionID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(competitionID)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>>("/api/v1/competitions/{competitionID}/participations", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsCompetitionIDParticipationsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1CompetitionsCompetitionIDParticipationsGetAsync(int competitionID, int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsCompetitionIDParticipationsGetWithHttpInfoAsync(competitionID, page, count, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>>> ApiV1CompetitionsCompetitionIDParticipationsGetWithHttpInfoAsync(int competitionID, int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("competitionID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(competitionID)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>>("/api/v1/competitions/{competitionID}/participations", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsCompetitionIDParticipationsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <returns></returns>
        public void ApiV1CompetitionsCompetitionIDParticipationsProfileIDDelete(int profileID, int competitionID)
        {
            ApiV1CompetitionsCompetitionIDParticipationsProfileIDDeleteWithHttpInfo(profileID, competitionID);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1CompetitionsCompetitionIDParticipationsProfileIDDeleteWithHttpInfo(int profileID, int competitionID)
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(profileID)); // path parameter
            localVarRequestOptions.PathParameters.Add("competitionID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(competitionID)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/v1/competitions/{competitionID}/participations/{profileID}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsCompetitionIDParticipationsProfileIDDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1CompetitionsCompetitionIDParticipationsProfileIDDeleteAsync(int profileID, int competitionID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsCompetitionIDParticipationsProfileIDDeleteWithHttpInfoAsync(profileID, competitionID, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1CompetitionsCompetitionIDParticipationsProfileIDDeleteWithHttpInfoAsync(int profileID, int competitionID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(profileID)); // path parameter
            localVarRequestOptions.PathParameters.Add("competitionID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(competitionID)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.DeleteAsync<Object>("/api/v1/competitions/{competitionID}/participations/{profileID}", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsCompetitionIDParticipationsProfileIDDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO</returns>
        public CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO ApiV1CompetitionsCompetitionIDParticipationsProfileIDGet(int profileID, int competitionID)
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> localVarResponse = ApiV1CompetitionsCompetitionIDParticipationsProfileIDGetWithHttpInfo(profileID, competitionID);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> ApiV1CompetitionsCompetitionIDParticipationsProfileIDGetWithHttpInfo(int profileID, int competitionID)
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(profileID)); // path parameter
            localVarRequestOptions.PathParameters.Add("competitionID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(competitionID)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>("/api/v1/competitions/{competitionID}/participations/{profileID}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsCompetitionIDParticipationsProfileIDGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO</returns>
        public async System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> ApiV1CompetitionsCompetitionIDParticipationsProfileIDGetAsync(int profileID, int competitionID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsCompetitionIDParticipationsProfileIDGetWithHttpInfoAsync(profileID, competitionID, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileID"></param>
        /// <param name="competitionID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1CompetitionsCompetitionIDParticipationsProfileIDGetWithHttpInfoAsync(int profileID, int competitionID, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(profileID)); // path parameter
            localVarRequestOptions.PathParameters.Add("competitionID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(competitionID)); // path parameter

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>("/api/v1/competitions/{competitionID}/participations/{profileID}", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsCompetitionIDParticipationsProfileIDGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="score"> (optional)</param>
        /// <returns></returns>
        public void ApiV1CompetitionsCompetitionIDParticipationsPut(int competitionID, int? score = default(int?))
        {
            ApiV1CompetitionsCompetitionIDParticipationsPutWithHttpInfo(competitionID, score);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="score"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1CompetitionsCompetitionIDParticipationsPutWithHttpInfo(int competitionID, int? score = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("competitionID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(competitionID)); // path parameter
            if (score != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "score", score));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/api/v1/competitions/{competitionID}/participations", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsCompetitionIDParticipationsPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="score"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1CompetitionsCompetitionIDParticipationsPutAsync(int competitionID, int? score = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1CompetitionsCompetitionIDParticipationsPutWithHttpInfoAsync(competitionID, score, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitionID"></param>
        /// <param name="score"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1CompetitionsCompetitionIDParticipationsPutWithHttpInfoAsync(int competitionID, int? score = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("competitionID", CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToString(competitionID)); // path parameter
            if (score != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "score", score));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PutAsync<Object>("/api/v1/competitions/{competitionID}/participations", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1CompetitionsCompetitionIDParticipationsPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <returns>List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        public List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO> ApiV1PlayersSelfParticipationsGet(int? page = default(int?), int? count = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> localVarResponse = ApiV1PlayersSelfParticipationsGetWithHttpInfo(page, count);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <returns>ApiResponse of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1PlayersSelfParticipationsGetWithHttpInfo(int? page = default(int?), int? count = default(int?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>>("/api/v1/players/self/participations", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersSelfParticipationsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> ApiV1PlayersSelfParticipationsGetAsync(int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayersSelfParticipationsGetWithHttpInfoAsync(page, count, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 0)</param>
        /// <param name="count"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>>> ApiV1PlayersSelfParticipationsGetWithHttpInfoAsync(int? page = default(int?), int? count = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<List<CompetitiveBackend.BackendUsage.Objects.PlayerParticipationDTO>>("/api/v1/players/self/participations", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayersSelfParticipationsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
