/*
 * CompetitiveBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CompetitiveFrontend.OpenAPIClient.Client;
using CompetitiveFrontend.OpenAPIClient.Model;

namespace CompetitiveFrontend.OpenAPIClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISelfPlayerApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO</returns>
        CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO ApiV1PlayerSelfGet();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO</returns>
        ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO> ApiV1PlayerSelfGetWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void ApiV1PlayerSelfImageGet();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1PlayerSelfImageGetWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"> (optional)</param>
        /// <returns></returns>
        void ApiV1PlayerSelfImagePost(System.IO.Stream? file = default(System.IO.Stream?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1PlayerSelfImagePostWithHttpInfo(System.IO.Stream? file = default(System.IO.Stream?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsPlayerProfileDTO"> (optional)</param>
        /// <returns></returns>
        void ApiV1PlayerSelfPatch(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO? competitiveBackendBackendUsageObjectsPlayerProfileDTO = default(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsPlayerProfileDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiV1PlayerSelfPatchWithHttpInfo(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO? competitiveBackendBackendUsageObjectsPlayerProfileDTO = default(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISelfPlayerApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO</returns>
        System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO> ApiV1PlayerSelfGetAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO>> ApiV1PlayerSelfGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1PlayerSelfImageGetAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1PlayerSelfImageGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1PlayerSelfImagePostAsync(System.IO.Stream? file = default(System.IO.Stream?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1PlayerSelfImagePostWithHttpInfoAsync(System.IO.Stream? file = default(System.IO.Stream?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsPlayerProfileDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiV1PlayerSelfPatchAsync(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO? competitiveBackendBackendUsageObjectsPlayerProfileDTO = default(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsPlayerProfileDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1PlayerSelfPatchWithHttpInfoAsync(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO? competitiveBackendBackendUsageObjectsPlayerProfileDTO = default(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISelfPlayerApi : ISelfPlayerApiSync, ISelfPlayerApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SelfPlayerApi : IDisposable, ISelfPlayerApi
    {
        private CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SelfPlayerApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public SelfPlayerApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SelfPlayerApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public SelfPlayerApi(string basePath)
        {
            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                new CompetitiveFrontend.OpenAPIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SelfPlayerApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public SelfPlayerApi(CompetitiveFrontend.OpenAPIClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CompetitiveFrontend.OpenAPIClient.Client.Configuration.MergeConfigurations(
                CompetitiveFrontend.OpenAPIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CompetitiveFrontend.OpenAPIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SelfPlayerApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public SelfPlayerApi(CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient client, CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient asyncClient, CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CompetitiveFrontend.OpenAPIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CompetitiveFrontend.OpenAPIClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CompetitiveFrontend.OpenAPIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO</returns>
        public CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO ApiV1PlayerSelfGet()
        {
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO> localVarResponse = ApiV1PlayerSelfGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO> ApiV1PlayerSelfGetWithHttpInfo()
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO>("/api/v1/player/self", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayerSelfGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO</returns>
        public async System.Threading.Tasks.Task<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO> ApiV1PlayerSelfGetAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayerSelfGetWithHttpInfoAsync(cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO> localVarResponse = await task.ConfigureAwait(false);
#else
            CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO)</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO>> ApiV1PlayerSelfGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO>("/api/v1/player/self", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayerSelfGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void ApiV1PlayerSelfImageGet()
        {
            ApiV1PlayerSelfImageGetWithHttpInfo();
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1PlayerSelfImageGetWithHttpInfo()
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/v1/player/self/image", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayerSelfImageGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1PlayerSelfImageGetAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayerSelfImageGetWithHttpInfoAsync(cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1PlayerSelfImageGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<byte[]>("/api/v1/player/self/image", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayerSelfImageGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return new ApiResponse<object>(localVarResponse.StatusCode, localVarResponse.Data);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"> (optional)</param>
        /// <returns></returns>
        public void ApiV1PlayerSelfImagePost(System.IO.Stream? file = default(System.IO.Stream?))
        {
            ApiV1PlayerSelfImagePostWithHttpInfo(file);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1PlayerSelfImagePostWithHttpInfo(System.IO.Stream? file = default(System.IO.Stream?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (file != null)
            {
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/api/v1/player/self/image", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayerSelfImagePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1PlayerSelfImagePostAsync(System.IO.Stream? file = default(System.IO.Stream?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayerSelfImagePostWithHttpInfoAsync(file, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1PlayerSelfImagePostWithHttpInfoAsync(System.IO.Stream? file = default(System.IO.Stream?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (file != null)
            {
                localVarRequestOptions.Data = file;
            }

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<Object>("/api/v1/player/self/image", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayerSelfImagePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsPlayerProfileDTO"> (optional)</param>
        /// <returns></returns>
        public void ApiV1PlayerSelfPatch(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO? competitiveBackendBackendUsageObjectsPlayerProfileDTO = default(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO?))
        {
            ApiV1PlayerSelfPatchWithHttpInfo(competitiveBackendBackendUsageObjectsPlayerProfileDTO);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsPlayerProfileDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object> ApiV1PlayerSelfPatchWithHttpInfo(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO? competitiveBackendBackendUsageObjectsPlayerProfileDTO = default(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO?))
        {
            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsPlayerProfileDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/v1/player/self", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayerSelfPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsPlayerProfileDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiV1PlayerSelfPatchAsync(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO? competitiveBackendBackendUsageObjectsPlayerProfileDTO = default(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            var task = ApiV1PlayerSelfPatchWithHttpInfoAsync(competitiveBackendBackendUsageObjectsPlayerProfileDTO, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="CompetitiveFrontend.OpenAPIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="competitiveBackendBackendUsageObjectsPlayerProfileDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CompetitiveFrontend.OpenAPIClient.Client.ApiResponse<Object>> ApiV1PlayerSelfPatchWithHttpInfoAsync(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO? competitiveBackendBackendUsageObjectsPlayerProfileDTO = default(CompetitiveBackend.BackendUsage.Objects.PlayerProfileDTO?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CompetitiveFrontend.OpenAPIClient.Client.RequestOptions localVarRequestOptions = new CompetitiveFrontend.OpenAPIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CompetitiveFrontend.OpenAPIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = competitiveBackendBackendUsageObjectsPlayerProfileDTO;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Bearer")))
            {
                localVarRequestOptions.HeaderParameters.Add("Bearer", this.Configuration.GetApiKeyWithPrefix("Bearer"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PatchAsync<Object>("/api/v1/player/self", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1PlayerSelfPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
