name: src
services:
  competitivebackend:
    build:
      context: D:\STUDWORK\sixth_semester\ppo\src
      dockerfile: CompetitiveBackend/Dockerfile
    depends_on:
      postgres:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          cpus: 2
          memory: "2147483648"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_HTTPS_PORTS: "8081"
      TELEMETRY_OLTP_ADDRESS: http://otel-collector:4317
    image: competitivebackend
    networks:
      my_persistent_network: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
      - mode: ingress
        target: 8080
        protocol: tcp
      - mode: ingress
        target: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: C:\Users\Ilya\AppData\Roaming/Microsoft/UserSecrets
        target: /home/app/.microsoft/usersecrets
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: C:\Users\Ilya\AppData\Roaming/Microsoft/UserSecrets
        target: /root/.microsoft/usersecrets
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: C:\Users\Ilya\AppData\Roaming/ASP.NET/Https
        target: /home/app/.aspnet/https
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: C:\Users\Ilya\AppData\Roaming/ASP.NET/Https
        target: /root/.aspnet/https
        read_only: true
        bind:
          create_host_path: true
  grafana:
    environment:
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_PATH_PROVISIONING: /etc/grafana/provisioning
      GF_SECURITY_ADMIN_PASSWORD: admin
    image: grafana/grafana
    networks:
      my_persistent_network: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    volumes:
      - type: bind
        source: D:\STUDWORK\sixth_semester\ppo\src\Benchmark\grafana\provisioning
        target: /etc/grafana/provisioning
        bind:
          create_host_path: true
      - type: bind
        source: D:\STUDWORK\sixth_semester\ppo\src\Benchmark\grafana\dashboards
        target: /var/lib/grafana/dashboards
        bind:
          create_host_path: true
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.57
    networks:
      my_persistent_network: null
    ports:
      - mode: ingress
        target: 16686
        published: "16686"
        protocol: tcp
  k6-s2:
    profiles:
      - scenario2
    command:
      - run
      - /scripts/scenarios/scenario2.js
      - --out
      - experimental-prometheus-rw
    container_name: k6
    depends_on:
      competitivebackend:
        condition: service_started
        required: true
      prometheus:
        condition: service_started
        required: true
    environment:
      K6_PROMETHEUS_RW_SERVER_URL: http://prometheus:9090/api/v1/write
      K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM: "true"
    image: grafana/k6:latest
    networks:
      my_persistent_network: null
    ports:
      - mode: ingress
        target: 6565
        published: "6565"
        protocol: tcp
    volumes:
      - type: bind
        source: D:\STUDWORK\sixth_semester\ppo\src\Benchmark\Advanced\K6Scenarios
        target: /scripts
        bind:
          create_host_path: true
      - type: bind
        source: D:\STUDWORK\sixth_semester\ppo\src\k6-output
        target: /output
        bind:
          create_host_path: true
  netdata:
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    container_name: netdata
    environment:
      NETDATA_PROMETHEUS_WEB: "yes"
    hostname: netdata
    image: netdata/netdata
    networks:
      my_persistent_network: null
    ports:
      - mode: ingress
        target: 19999
        published: "19999"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true
  otel-collector:
    command:
      - --config=/etc/otel/otel-collector-config.yaml
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    networks:
      my_persistent_network: null
    ports:
      - mode: ingress
        target: 4317
        published: "4317"
        protocol: tcp
      - mode: ingress
        target: 4318
        published: "4318"
        protocol: tcp
      - mode: ingress
        target: 9464
        published: "9464"
        protocol: tcp
    volumes:
      - type: bind
        source: D:\STUDWORK\sixth_semester\ppo\src\otel-collector-config.yml
        target: /etc/otel/otel-collector-config.yaml
        bind:
          create_host_path: true
  postgres:
    container_name: database
    deploy:
      resources:
        limits:
          cpus: 2
          memory: "2147483648"
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: maindb
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: root
    image: postgres
    networks:
      my_persistent_network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
        volume: {}
      - type: bind
        source: D:\STUDWORK\sixth_semester\ppo\src\postgres\init
        target: /docker-entrypoint-initdb.d
        bind:
          create_host_path: true
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/console_templates
      - --storage.tsdb.retention.time=200h
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
    image: prom/prometheus
    networks:
      my_persistent_network: null
    ports:
      - mode: ingress
        target: 9090
        published: "9090"
        protocol: tcp
    volumes:
      - type: bind
        source: D:\STUDWORK\sixth_semester\ppo\src\prometheus.yml
        target: /etc/prometheus/prometheus.yml
        bind:
          create_host_path: true
      - type: volume
        source: prometheus-data
        target: /prometheus
        volume: {}
networks:
  my_persistent_network:
    name: src_my_persistent_network
    driver: bridge
volumes:
  database-data:
    name: src_database-data
  prometheus-data:
    name: src_prometheus-data
